version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - ./config/.development.env
    volumes:
      - .:/app
    ports:
      -  3000:3000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: library/postgres:13-alpine
    env_file:
      - ./config/.development.env
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "igor"
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    restart: always


